title = "Summer Rental"
baseURL = "https://summer-rental-in-ocean-grove-nj.netlify.com/"
languageCode = "en"
theme = "gohugo-theme-ananke"
disqusShortname = "ananke-demo"
MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
disableKinds = ["page","section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]

[params]
  description = "Spacious and clean, modern Victorian with 4 bedrooms, 2 ½ baths that sleeps 8."
  faceboook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/uploads/house.jpg"
